### ISSUE TITLE
Launcher crashes when clicking home button.

### ISSUE THREAD

**Issue by OmegaSunkey** [kennethnym/StarlightLauncher#18]
Device: Samsung J7 2016
ROM: Klaxosaur V1
Based on: One Ui Core 2.0, Android 10
App Version: 1.0.0-beta.5, downloaded from Google Play.

Issue:
- Launcher crashes at the moment of going home.
• Steps to reproduce:
  - Click home

Stacktrace:
```
FATAL EXCEPTION: main
Process: kenneth.app.starlightlauncher, PID: 17504
java.lang.RuntimeException: Unable to destroy activity {kenneth.app.starlightlauncher/kenneth.app.starlightlauncher.MainActivity}: java.lang.IllegalArgumentException: Receiver not registered: l4.g$b@8cdc5ca
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5326)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:5360)
	at android.app.servertransaction.DestroyActivityItem.execute(DestroyActivityItem.java:44)
	at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
Caused by: java.lang.IllegalArgumentException: Receiver not registered: l4.g$b@8cdc5ca
	at android.app.LoadedApk.forgetReceiverDispatcher(LoadedApk.java:1499)
	at android.app.ContextImpl.unregisterReceiver(ContextImpl.java:1604)
	at android.content.ContextWrapper.unregisterReceiver(ContextWrapper.java:678)
	at l4.g.c(SourceFile:3)
	at kenneth.app.starlightlauncher.MainActivity.onDestroy(SourceFile:6)
	at android.app.Activity.performDestroy(Activity.java:8217)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1342)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:5311)
	... 11 more
```

**Comment by kennethnym** [comment]
I know why this is happening (thanks for the stack trace!), will fix.

**Comment by OmegaSunkey** [comment]
Beta-6 
![20220827_144640](https://user-images.githubusercontent.com/94485936/187045823-857c4977-496a-4e23-a3b5-4208366d68b4.jpg)
These 3 errors happen now.

**Comment by kennethnym** [comment]
This is strange - I cannot reproduce this issue on my part. Are you pressing the home button when you are already on the home screen?

**Comment by OmegaSunkey** [comment]
as the launcher crashes, im on the default home screen, so to spawn the selected launcher you have to click home again, but those errors happen when you do it

**Comment by OmegaSunkey** [comment]
also happens if you are in an app

**Comment by kennethnym** [comment]
So when you are in an app, and you press home to go back to Starlight, it crashes right away?

**Comment by OmegaSunkey** [comment]
yop

**Comment by kennethnym** [comment]
Would you mind reinstalling the app to see if it will happen again?

**Comment by OmegaSunkey** [comment]
it is normal that stock launcher is visible for 3 seconds then starlight appears again

**Comment by kennethnym** [comment]
Might be related to #35

**Comment by meisme-dev** [comment]
I know this is an old issue, but I can reproduce this consistently on a stock S9+. Might be related to OneUI

**Comment by kennethnym** [comment]
This is weird, because I am using Starlight daily on my S20+, and I haven't encountered this issue. I will try to investigate.
