### ISSUE TITLE
Crashes on start

### ISSUE THREAD

**Issue by donenoyes** [kennethnym/StarlightLauncher#4]
When launched, app crashes:

```
2021-04-16 18:05:17.259 4473-4473/kenneth.app.spotlightlauncher E/AndroidRuntime: FATAL EXCEPTION: main
    Process: kenneth.app.spotlightlauncher, PID: 4473
    java.lang.RuntimeException: Unable to start activity ComponentInfo{kenneth.app.spotlightlauncher/kenneth.app.spotlightlauncher.MainActivity}: android.view.InflateException: Binary XML file line #56 in kenneth.app.spotlightlauncher:layout/activity_main: Binary XML file line #56 in kenneth.app.spotlightlauncher:layout/activity_main: Error inflating class kenneth.app.spotlightlauncher.views.LauncherScrollView
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3310)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3459)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2046)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:225)
        at android.app.ActivityThread.main(ActivityThread.java:7564)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: android.view.InflateException: Binary XML file line #56 in kenneth.app.spotlightlauncher:layout/activity_main: Binary XML file line #56 in kenneth.app.spotlightlauncher:layout/activity_main: Error inflating class kenneth.app.spotlightlauncher.views.LauncherScrollView
     Caused by: android.view.InflateException: Binary XML file line #56 in kenneth.app.spotlightlauncher:layout/activity_main: Error inflating class kenneth.app.spotlightlauncher.views.LauncherScrollView
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:343)
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/view/WindowInsetsAnimation$Callback;
        at java.lang.reflect.Constructor.newInstance0(Native Method) 

2021-04-16 18:05:17.259 4473-4473/kenneth.app.spotlightlauncher E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.view.WindowInsetsAnimation$Callback" on path: DexPathList[[zip file "/data/app/kenneth.app.spotlightlauncher-SZfm1051ekcBqWhRMzcw2g==/base.apk"],nativeLibraryDirectories=[/data/app/kenneth.app.spotlightlauncher-SZfm1051ekcBqWhRMzcw2g==/lib/arm64, /data/app/kenneth.app.spotlightlauncher-SZfm1051ekcBqWhRMzcw2g==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
```

**Comment by kennethnym** [comment]
Hi @donenoyes, didn't expect an issue here! I've pushed a lot of updates since then, can you try running the launcher again and see if it still crashes? On first prompt of allowing file permission it WILL crash because in prod there will be a proper onboarding flow to explain everything. If you open the launcher again afterwards, it should work.
