### ISSUE TITLE
Crashing when calculating 4-3

### ISSUE THREAD

**Issue by 0BFG** [kennethnym/StarlightLauncher#75]
Just typed 4-3 in the search bar and it crashes everytime

java.util.regex.PatternSyntaxException: In a character range [x-y], x is greater than y near index 4
[4-3]
    ^
	at com.android.icu.util.regex.PatternNative.compileImpl(Native Method)
	at com.android.icu.util.regex.PatternNative.<init>(PatternNative.java:53)
	at com.android.icu.util.regex.PatternNative.create(PatternNative.java:49)
	at java.util.regex.Pattern.compile(Pattern.java:1446)
	at java.util.regex.Pattern.<init>(Pattern.java:1421)
	at java.util.regex.Pattern.compile(Pattern.java:998)
	at p8.d.<init>(SourceFile:4)
	at h5.b.run(SourceFile:3)
	at java.util.TimerThread.mainLoop(Timer.java:563)
	at java.util.TimerThread.run(Timer.java:513)

**Comment by kennethnym** [comment]
I am aware of this issue, I am in the process of addressing the bug. Thanks for reporting!
